#!/bin/bash
if [[ -z "$1" ]]; then
  >&2 echo "You need to pass the splunk package tarball"
  exit 1
else
  sudo tar -xvzf $1 -C /opt
  if [[ $? -nq 0 ]]; then
    exit 1
  fi
  sudo chown -R `whoami`:`whoami` /opt/splunk*
  source /opt/splunk*/bin/setSplunkEnv
  splunk start --accept-license --answer-yes --no-prompt --seed-passwd admin123
fi
